### ISSUE TITLE
Name Suggestion for the Standard Formula / Gardner Formula

### ISSUE THREAD

**Issue by aschet** [m-schmidt/Refracto#3]
Fellow refractometer correction formula aficionado without an iOS device here. The formula called "Standard" in the application is a model that was derived by Louis K. Bonham and published in the article "The Use of Handheld Refractometers by Homebrewers" in the Zymurgy January/February 2001 issue. So I suggest to change its name to "Bonham" (without any serious intent).

This might be of your interest: the article mentioned above references another refractometer correction model formulated by Steven D. Gardner. From the article:

SG = 1.53 R - 0.59 OG
R = Refractometer reading of the beer*
OG = Original gravity of the beer (in degrees Plato)
SG = Specific gravity of the beer (in degrees Plato)

*) apparently without correction factor applied

**Comment by m-schmidt** [comment]
Thank you for the hint. I probably cannot update the UI since most users are unfamiliar with the correct name and refer only to the "standard" formula. However, I will mention the name in the source code and on the website/documentation.

**Comment by aschet** [comment]
This is probably the most sensible way forward, thank you for consideration!

**Comment by m-schmidt** [comment]
Added comment/updated README with commit f38c51fb845a4b4eb72eb43157060f59626241d0
